#!/usr/bin/env python

def build(bld):
  bld.install_files('${PREFIX}/include/elog', bld.path.ant_glob('*.h'))

  bld(features = 'cxx cprogram gtest',
      source = 'logger_test.cc',
      target = 'logger_test')
  bld(features = 'cxx cprogram gtest',
      source = 'stream_logger_test.cc',
      target = 'stream_logger_test')
  bld(features = 'cxx cprogram gtest',
      source = 'thread_test.cc',
      target = 'thread_test')
  bld(features = 'cxx cprogram gtest',
      source = 'mutex_test.cc',
      target = 'mutex_test')
  bld(features = 'cxx cprogram gtest',
      source = 'type_info_test.cc',
      target = 'type_info_test')
